version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5400:5400"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres